function A = A_i(t, d, a, alf)
A = [cos(t) (-sin(t)*cos(alf)) (sin(t)*sin(alf)) (a*cos(t));...
    sint(t) (cos(t)*cos(alf)) (-cos(t)*cos(alf)) a*sin(t);...
    0 sin(alf) cos(a) d;...
    0 0 0 1];
